Creates a default name for the constant based on valid naming characters
arazmakhnin/cc-tools pull request #3
Opened 2019-07-05 16:29 UTC by LucasTaves

# Changes
- Uses the string content as a way to name the created constants

2019-07-05 17:29 UTC, arazmakhnin requested changes
Please fix highlighted issues.
Also, there are two additional points:
1. Newly created constants should be differ from existed ones. ICs should know what constants they should check and rename, and what constants they shouldn't touch. Maybe with commented line or something else...
2. Please fix unit tests :)

2019-07-05 17:29 UTC, arazmakhnin commented on CcWorks/Workers/Solvers/BrpMagicStringsSolver.cs
> +                @"[^\w]",
`\W` can be used here instead of `[^\w]`

2019-07-05 17:29 UTC, arazmakhnin commented on CcWorks/Workers/Solvers/BrpMagicStringsSolver.cs
> +        private static string GetConstantName(string constantSubstring)
This function should also:
- trim leading numbers
- truncate long names to (for example) 30 chars
- check if result name is empty of whitespace, then return default unique name

2019-07-05 17:36 UTC, LucasTaves commented
Didn't saw your comments, fixing it now

2019-07-10 10:38 UTC, arazmakhnin approved these changes

2019-07-10 10:38 UTC, merged